/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thalmic_myo_Hub */

#ifndef _Included_com_thalmic_myo_Hub
#define _Included_com_thalmic_myo_Hub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thalmic_myo_Hub
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Hub_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_thalmic_myo_Hub
 * Method:    waitForMyo
 * Signature: (I)Lcom/thalmic/myo/Myo;
 */
JNIEXPORT jobject JNICALL Java_com_thalmic_myo_Hub_waitForMyo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Hub
 * Method:    addListener
 * Signature: (Lcom/thalmic/myo/DeviceListener;)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Hub_addListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_thalmic_myo_Hub
 * Method:    removeListener
 * Signature: (Lcom/thalmic/myo/DeviceListener;)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Hub_removeListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_thalmic_myo_Hub
 * Method:    run
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Hub_run
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Hub
 * Method:    runOnce
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Hub_runOnce
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Hub
 * Method:    setLockingPolicy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Hub_setLockingPolicy
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
