/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thalmic_myo_Myo */

#ifndef _Included_com_thalmic_myo_Myo
#define _Included_com_thalmic_myo_Myo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thalmic_myo_Myo
 * Method:    vibrate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo_vibrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    requestRssi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo_requestRssi
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    unlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo_unlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo_lock
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    notifyUserAction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo_notifyUserAction
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    setStreamEmg
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo_setStreamEmg
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
